Feature/multiples of 3 and 5
diliaaragon/Ruby-exercises pull request #1
Opened 2019-01-21 20:00 UTC by diliaaragon

2019-01-22 20:44 UTC, juankhazbun requested changes

2019-01-22 20:44 UTC, juankhazbun commented on maths.rb
> +    return suma3, suma5 #[3, 5]
Borra el comentario.

2019-01-22 20:44 UTC, juankhazbun commented on maths.rb
> +    suma3 = 0
Inicializa las dos variables en una misma linea.

2019-01-22 20:44 UTC, juankhazbun commented on maths.rb
> +    (0..1000).each do |i|
Recibe el número hasta el cual quieres encontrar la suma como un parámetro.

2019-01-23 16:36 UTC, diliaaragon commented on maths.rb
> +    return suma3, suma5 #[3, 5]
listo

2019-01-23 16:36 UTC, diliaaragon commented on maths.rb
> +    suma3 = 0
listo

2019-01-23 16:41 UTC, diliaaragon commented on maths.rb
> +    (0..1000).each do |i|
listo

2019-01-28 14:27 UTC, juankhazbun approved these changes

2019-01-28 14:27 UTC, merged