Add sum of the even fibonacci numbers until 4000000
diliaaragon/Ruby-exercises pull request #2
Opened 2019-01-21 22:22 UTC by diliaaragon

2019-01-22 20:45 UTC, juankhazbun requested changes

2019-01-22 20:45 UTC, juankhazbun commented on maths.rb
> +    while c <= 4000000
Recibe el número fibonacci mas alto como parámetro.

2019-01-22 20:45 UTC, juankhazbun commented on maths.rb
> +    a = 1
Trata de que las asignaciones te queden en menor número de lineas.

2019-01-23 16:20 UTC, diliaaragon commented on maths.rb
> +    while c <= 4000000
listo

2019-01-23 16:24 UTC, diliaaragon commented on maths.rb
> +    a = 1
listo

2019-01-28 15:00 UTC, juankhazbun approved these changes

2019-01-28 15:00 UTC, merged