largest prime factor method
diliaaragon/Ruby-exercises pull request #3
Opened 2019-01-22 14:35 UTC by diliaaragon

2019-01-22 20:46 UTC, juankhazbun requested changes

2019-01-22 20:46 UTC, juankhazbun commented on main.rb
> +puts  " the prime largest is #{prime_largest}"
Debe ser "The largest prime factor is ..."

2019-01-22 20:46 UTC, juankhazbun commented on maths.rb
> +    y = 600851475143
Recibe el número como parámetro de la función.

2019-01-22 20:46 UTC, juankhazbun commented on maths.rb
> +       arr << is_prime?(i)
No es necesario que guardes los números en un array si solo vas a retornar el máximo.

2019-01-22 20:58 UTC, diliaaragon commented on main.rb
> +puts  " the prime largest is #{prime_largest}"
listo

2019-01-22 20:59 UTC, diliaaragon commented on maths.rb
> +    y = 600851475143
listo

2019-01-23 15:01 UTC, diliaaragon commented on maths.rb
> +       arr << is_prime?(i)
listo

2019-01-28 15:58 UTC, juankhazbun approved these changes

2019-01-28 15:58 UTC, juankhazbun commented on maths.rb
> +        num_prime = i if is_prime?(i)
Tienes 2 if que pueden estar en una misma linea.

2019-01-28 15:58 UTC, juankhazbun commented on maths.rb
> +    is_prime = true
Esta variable no la utilizas en ninguna parte del código.

2019-01-28 15:58 UTC, merged